[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
verbosity = 2
fs_permissions = [
    { access = "read", path = "./test" },
    { access = "read", path = "./script" },
]
ignored_warnings = { "5667" = ["src/Halo2Verifier.sol"], "2018" = ["src/Halo2Verifier.sol"] }

[rpc_endpoints]
anvil = "http://localhost:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
